# -----------------------------
# BLUE DEPLOYMENT
# -----------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.global.appName }}-blue"
  namespace: "{{ .Values.global.namespace }}"
spec:
  replicas: {{ .Values.deployment.blue.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.global.appName }}"
      version: blue
  template:
    metadata:
      labels:
        app: "{{ .Values.global.appName }}"
        version: blue
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: "{{ .Values.global.appName }}"
          image: "{{ .Values.blue.image.repository }}:{{ .Values.blue.image.tag }}"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: {{ .Values.deployment.resources.requests.cpu }}
              memory: {{ .Values.deployment.resources.requests.memory }}
            limits:
              cpu: {{ .Values.deployment.resources.limits.cpu }}
              memory: {{ .Values.deployment.resources.limits.memory }}
          startupProbe:
            tcpSocket:
              port: 7361
            # fakehost has 60 seconds to start
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
          readinessProbe:
            tcpSocket:
              port: 7361
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 7361
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10

---

# -----------------------------
# GREEN DEPLOYMENT
# -----------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.global.appName }}-green"
  namespace: "{{ .Values.global.namespace }}"

spec:
  replicas: {{ .Values.deployment.green.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.global.appName }}"
      version: green
  template:
    metadata:
      labels:
        app: "{{ .Values.global.appName }}"
        version: green
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: "{{ .Values.global.appName }}"
          image: "{{ .Values.green.image.repository }}:{{ .Values.green.image.tag }}"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: {{ .Values.deployment.resources.requests.cpu }}
              memory: {{ .Values.deployment.resources.requests.memory }}
            limits:
              cpu: {{ .Values.deployment.resources.limits.cpu }}
              memory: {{ .Values.deployment.resources.limits.memory }}
          startupProbe:
            tcpSocket:
              port: 7361
            # fakehost has 60 seconds to start
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
          readinessProbe:
            tcpSocket:
              port: 7361
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 7361
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10