apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "{{ .Values.global.appName }}-dr"
  namespace: "{{ .Values.global.namespace }}"
spec:
  host: "{{ .Values.global.appName }}.{{ .Values.global.namespace }}.svc.cluster.local"

  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN

    connectionPool:
      tcp:
        maxConnections: 100

      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 10

    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 50

  subsets:
    - name: blue
      labels:
        version: blue

    - name: green
      labels:
        version: green