{{- if .Values.global.deploy.useDocumentDB }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentdbproxy
spec:
  replicas: {{ .Values.documentdbproxy.replicas }}
  selector:
    matchLabels:
      app: documentdbproxy
  template:
    metadata:
      labels:
        app: documentdbproxy
    spec:
      containers:
        - env:
            - name: MODE
              value: tcp
            - name: HOST
              value: {{ .Values.global.deploy.docdbhost | quote }}
            - name: FRONTEND_PORT
              value: "27017"
            - name: BACKEND_PORT
              value: "27017"
          image: docker-registry.sandstone.com.au/docker/sst_haproxy:0.1.5453
          imagePullPolicy: IfNotPresent
          name: documentdbproxy
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: sst-docker-registry-key
      restartPolicy: Always
      schedulerName: default-scheduler
{{- end }}