apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakehost
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakehost
  template:
    metadata:
      labels:
        app: fakehost
    spec:
      containers:
      - image: docker-registry.sandstone.com.au/docker/{{ .Values.global.deploy.containerImage.fakehost }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: fakehost
        startupProbe:
          tcpSocket:
            port: 7361
          # fakehost has 60 seconds to start
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 12
        readinessProbe:
          tcpSocket:
            port: 7361
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
          successThreshold: 1
        livenessProbe:
          tcpSocket:
            port: 7361
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
      restartPolicy: Always
      imagePullSecrets:
        - name: sst-docker-registry-key
---
apiVersion: v1
kind: Service
metadata:
  name: fakehost
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - name: host
    port: 7361
  - name: lmi
    port: 7708
  selector:
    app: fakehost
