apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcastmanagementcenter
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  # hazelcastmanagementcenter doesn't have any replicas by default as it's just a troubleshooting tool
  replicas: 0
  selector:
    matchLabels:
      app: hazelcastmanagementcenter
  template:
    metadata:
      labels:
        app: hazelcastmanagementcenter
    spec:
      containers:
      - image: docker-registry.sandstone.com.au/docker/oops_hazelcastmanagementcenter:hazelcastmanagementcenter-86
        name: hazelcastmanagementcenter
        imagePullPolicy: {{ .Values.imagePullPolicy }}
      restartPolicy: Always
      imagePullSecrets:
        - name: sst-docker-registry-key
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcastmanagementcenter
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - port: 8080
  selector:
    app: hazelcastmanagementcenter
