apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: support-ingress-landing
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /index.html
    nginx.ingress.kubernetes.io/upstream-vhost: $host
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  rules:
  - host: {{ .Values.global.deploy.internal_gateway }}
    http:
      paths:
      - path: /portal
        pathType: Prefix
        backend:
          service:
            name: landing
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: landing
            port:
              number: 8080
  {{- if .Values.global.deploy.useManagementGateway }}
  - host: {{ .Values.global.deploy.management_gateway }}
    http:
      paths:
      - path: /portal
        pathType: Prefix
        backend:
          service:
            name: landing
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: landing
            port:
              number: 8080
  {{- end }}