# Expose internal services for API testing.
# Remove context root using rewrite, see https://kubernetes.github.io/ingress-nginx/examples/rewrite/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: support-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/custom-headers: "{{ .Release.Namespace }}/ingress-custom-headers-configmap-with-csp"
    nginx.ingress.kubernetes.io/upstream-vhost: $host
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  rules:
  - host: {{ .Values.global.deploy.internal_gateway }}
    http:
      paths:
      - path: /livingcostservice(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: livingcostservice
            port:
              number: 8080
      - path: /productmanager(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: productmanager
            port:
              number: 8080
      - path: /taxservice(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: taxservice
            port:
              number: 8080
      - path: /serviceabilityservice(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: serviceabilityservice
            port:
              number: 8080
      - path: /applyproductmanager(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: applyproductmanager
            port:
              number: 8080
---
# Declared separate ingress for wso2 as the 'rewrite-target' annotation on 'support-ingress' conflicts with wso2-is.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wso2-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-redirect-from: "https://{{ .Values.global.deploy.external_gateway }}/oauth2/"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://{{ .Values.global.deploy.external_gateway }}/wso2-is/oauth2/"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/custom-headers: "{{ .Release.Namespace }}/ingress-custom-headers-configmap-with-csp"
    nginx.ingress.kubernetes.io/upstream-vhost: $host
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  rules:
  - host: {{ .Values.global.deploy.external_gateway }}
    http:
      paths:
      - path: /wso2-is
        pathType: Prefix
        backend:
          service:
            name: wso2is
            port:
              number: 9763
  {{- if .Values.global.deploy.useManagementGateway }}
  - host: {{ .Values.global.deploy.management_gateway }}
    http:
      paths:
      - path: /wso2-is
        pathType: Prefix
        backend:
          service:
            name: wso2is
            port:
              number: 9763
  {{- end }}
---
# Declared separate ingress for mailhog as the 'rewrite-target' annotation on 'support-ingress' conflicts with mailhog.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailhog-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  rules:
  - host: {{ .Values.global.deploy.internal_gateway }}
    http:
      paths:
      - path: /{{ .Values.mailhog.webPath }}
        pathType: Prefix
        backend:
          service:
            name: mailhog
            port:
              number: 8025
  {{- if .Values.global.deploy.useManagementGateway }}
  - host: {{ .Values.global.deploy.management_gateway }}
    http:
      paths:
      - path: /{{ .Values.mailhog.webPath }}
        pathType: Prefix
        backend:
          service:
            name: mailhog
            port:
              number: 8025
  {{- end }}
