apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
      - image: docker-registry.sandstone.com.au/docker/{{ .Values.global.deploy.containerImage.landing }}
        name: landing
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
          - name: HOST_SERVER
            value: {{ .Values.global.deploy.internal_gateway }}
        {{- if .Values.front_end.startupProbe.enabled }}
        startupProbe:
          httpGet:
            path: '/'
            port: 8080
          periodSeconds: {{ .Values.front_end.startupProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.front_end.startupProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.front_end.startupProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.front_end.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: '/'
            port: 8080
          periodSeconds: {{ .Values.front_end.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.front_end.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.front_end.readinessProbe.failureThreshold }}
          successThreshold: {{ .Values.front_end.readinessProbe.successThreshold }}
        {{- end }}
        {{- if .Values.front_end.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: '/'
            port: 8080
          periodSeconds: {{ .Values.front_end.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.front_end.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.front_end.livenessProbe.failureThreshold }}
        {{- end }}
      imagePullSecrets:
      - name: sst-docker-registry-key
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: landing
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: http-alt
    port: 8080
  - name: https-alt
    port: 8443
  selector:
    app: landing
