apiVersion: apps/v1
kind: Deployment
metadata:
  name: smsapi
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.smsapi.replicas }}
  selector:
    matchLabels:
      app: smsapi
  template:
    metadata:
      labels:
        app: smsapi
    spec:
      restartPolicy: Always
      containers:
        - name: smsapi2email
          image: docker-registry.sandstone.com.au/docker/{{ .Values.global.deploy.containerImage.smsapi2email }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
            limits:
              memory: '128Mi'
            requests:
              memory: '50Mi'
          env:
            - name: SMTP_HOST
              value: {{ .Values.smsapi.smtpHost | quote }}
            - name: SMTP_PORT
              value: {{ .Values.smsapi.smtpPort | quote }}
            - name: DOMAIN
              value: abank-{{ .Release.Namespace }}
      imagePullSecrets:
        - name: sst-docker-registry-key
---
apiVersion: v1
kind: Service
metadata:
  name: smsapi
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 8080
  selector:
    app: smsapi
