apiVersion: apps/v1
kind: Deployment
metadata:
  name: titlesearchfakehost
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titlesearchfakehost
  template:
    metadata:
      labels:
        app: titlesearchfakehost
    spec:
      containers:
      - image: docker-registry.sandstone.com.au/docker/{{ .Values.global.deploy.containerImage.titlesearchfakehost }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: titlesearchfakehost
      restartPolicy: Always
      imagePullSecrets:
        - name: sst-docker-registry-key
---
apiVersion: v1
kind: Service
metadata:
  name: titlesearchfakehost
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - port: 7711
  selector:
    app: titlesearchfakehost
