apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremockservice
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiremockservice
  template:
    metadata:
      labels:
        app: wiremockservice
    spec:
      containers:
      - image: docker-registry.sandstone.com.au/docker/{{ .Values.global.deploy.containerImage.wiremockservice }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: wiremockservice
        startupProbe:
          httpGet:
            path: '/health'
            port: 8080
          # wiremockservice has 60s to start
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 12
        readinessProbe:
          httpGet:
            path: '/health'
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: '/health'
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
      restartPolicy: Always
      imagePullSecrets:
        - name: sst-docker-registry-key
---
apiVersion: v1
kind: Service
metadata:
  name: wiremockservice
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - name: host
    port: 8080
  selector:
    app: wiremockservice
