# Blue Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.global.appName }}-blue"
spec:
  replicas: {{ .Values.deployment.blue.replicas }}

---
# Green Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.global.appName }}-green"
spec:
  replicas: {{ .Values.deployment.green.replicas }}
