apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "{{ .Values.global.appName }}-dr"
spec:
  host: "{{ .Values.global.appName }}.{{ .Values.global.namespace }}.svc.cluster.local"
  subsets:
    - name: blue
      labels:
        version: blue
    - name: green
      labels:
        version: green
