apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.global.appName }}"
spec:
  selector:
    app: "{{ .Values.global.appName }}"
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8880
  sessionAffinity: ClientIP
