global:
  namespace: prod
  appName: fakehost

blue:
  image:
    repository: docker-registry.sandstone.com.au/docker/abank_fakehost #blue-green-istio-platform
    tag: 0.1.5418

green:
  image:
    repository: docker-registry.sandstone.com.au/docker/abank_fakehost
    tag: 0.1.5449

service:
  port: 80
  targetPort: 8080

deployment:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

  blue:
    replicas: 4
  green:
    replicas: 0

virtualService:
  host: "*"
  gateway: istio-system/ingressgateway
  timeout: 300s
  weights:
    blue: 100
    green: 0

hpa:
  blue:
    minReplicas: 4
    maxReplicas: 10
    cpuTarget: 75

  green:
    minReplicas: 1
    maxReplicas: 15
    cpuTarget: 60